
   "Holiday Twisteds",
   "Others"
];

// * キャラクター情報（編集可能。最後の行に”,”を付けないようにしてください）
// * 使用フラグ（0にするとソートに入りません）, 
//   "タイトルID"（先頭から0, 1, 2...）, 
//   {タイトル別参加フラグ}（1を入れると対象タイトルに入ります）,
//   "キャラクター名", "画像（空白の場合、キャラクター名が使用されます）"
//                                      [1,2,3,4,5,6,7,8,9,
var ary_CharacterData = [
  [1, "Dandy", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Dandy_Render.png"],
  [1, "Astro", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Astro_Render.png"],
  [1, "Sprout", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Sprout_Render.png"],
  [1, "Pebble", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Pebble_Render.png"],
  [1, "Shelly", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Shelly_Render.png"],
  [1, "Vee", [1,0,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Vee_Render.png"],
  [1, "Bassie", [1,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Bassie_Render.png"],
  [1, "Bobette", [1,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Bobette_Render.png"],
  [1, "Poppy", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Poppy_Render.png"],
  [1, "Boxten", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Boxten_Render.png"],
  [1, "Tisha", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Tisha_Render.png"],
  [1, "Toodles", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Toodles_Render.png"],
  [1, "Looey", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Looey_Render.png"],
  [1, "Finn", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Finn_Render.png"],
  [1, "Flutter", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Flutter_Render.png"],
  [1, "Gigi", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Gigi_Render.png"],
  [1, "Glisten", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Glisten_Render.png"],
  [1, "Goob", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Goob_Render.png"],
  [1, "Razzle & Dazzle", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Razzle_&_Dazzle_Render.png"],
  [1, "Rodger", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Rodger_Render.png"],
  [1, "Scraps", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Scraps_Render.png"],
  [1, "Shrimpo", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Shrimpo_Render.png"],
  [1, "Teagan", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Teagan_Render.png"],
  [1, "Yatta", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Yatta_Render.png"],
  [1, "Cosmo", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Cosmo_Render.png"],
  [1, "Connie", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Connie_Render.png"],
  [1, "Brightney", [0,1,0,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Brightney_Render.png"],
  [1, "Cocoa", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Cocoa_Render.png"],
  [1, "Eggson", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Eggson_Render.png"],
  [1, "Flyte", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Flyte_Render.png"],
  [1, "Coal", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Coal_Render.png"],
  [1, "Ginger", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Ginger_Render.png"],
  [1, "Rudie", [0,0,1,0,0,0,0], "https://github.com/ibroquentin/dandys_world_sort/blob/master/Touhou%20Character%20Sorting_files/Rudie_Render.png"]
  [1, "Twisted Dandy", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Dandy_Render.png"],
  [1, "Twisted Astro", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Astro_Render.png"],
  [1, "Twisted Sprout", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Sprout_Render.png"],
  [1, "Twisted Pebble", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Pebble_Render.png"],
  [1, "Twisted Shelly", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Shelly_Render.png"],
  [1, "Twisted Vee", [0,0,0,1,0,0,0], "Touhou Character Sorting_files/Twisted_Vee_Render.png"],
  [1, "Twisted Bassie", [0,0,0,1,0,1,0], "Touhou Character Sorting_files/Twisted_Bassie_Render.png"],
  [1, "Twisted Bobette", [0,0,0,1,0,1,0], "Touhou Character Sorting_files/Twisted_Bobette_Render.png"],
  [1, "Twisted Poppy", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Poppy_Render.png"],
  [1, "Twisted Boxten", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Boxten_Render.png"],
  [1, "Twisted Tisha", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Tisha_Render.png"],
  [1, "Twisted Toodles", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Toodles_Render.png"],
  [1, "Twisted Looey", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Looey_Render.png"],
  [1, "Twisted Finn", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Finn_Render.png"],
  [1, "Twisted Flutter", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Flutter_Render.png"],
  [1, "Twisted Gigi", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Gigi_Render.png"],
  [1, "Twisted Glisten", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Glisten_Render.png"],
  [1, "Twisted Goob", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Goob_Render.png"],
  [1, "Twisted Razzle & Dazzle", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Razzle_&_Dazzle_Render.png"],
  [1, "Twisted Rodger", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Rodger_Render.png"],
  [1, "Twisted Scraps", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Scraps_Render.png"],
  [1, "Twisted Shrimpo", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Shrimpo_Render.png"],
  [1, "Twisted Teagan", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Teagan_Render.png"],
  [1, "Twisted Yatta", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Yatta_Render.png"],
  [1, "Twisted Cosmo", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Cosmo_Render.png"],
  [1, "Twisted Connie", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Connie_Render.png"],
  [1, "Twisted Brightney", [0,0,0,0,1,0,0], "Touhou Character Sorting_files/Twisted_Brightney_Render.png"],
  [1, "Twisted Cocoa", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Cocoa_Render.png"],
  [1, "Twisted Eggson", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Eggson_Render.png"],
  [1, "Twisted Flyte", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Flyte_Render.png"],
  [1, "Twisted Coal", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Coal_Render.png"],
  [1, "Twisted Ginger", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Ginger_Render.png"],
  [1, "Twisted Rudie", [0,0,0,0,0,1,0], "Touhou Character Sorting_files/Twisted_Rudie_Render.png"]
];
